Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// for Backend:

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    //include_route_files(__DIR__.'/backend/');
    Route::group([
        'prefix'     => 'settings',
        'as'         => 'settings.',
        //'namespace'  => 'Crud',
    ], function () {
        Route::group([
            'middleware' => 'permission:edit settings',
        ], function () {
            Route::get('', 'SettingsController@index')->name('index');
            Route::post('', 'SettingsController@store')->name('store');

            //Route::get('datatabledata', 'SettingsController@datatabledata')->name('datatabledata');
            //Route::any('export/{filter?}', 'SettingsController@export')->name('export');

            //Route::get('edit/{id}', 'SettingsController@edit')->name('edit');
            //Route::get('create', 'SettingsController@create')->name('create');
            //Route::any('update/{id?}', 'SettingsController@update')->name('update');
            //Route::any('delete/{organisation}', 'SettingsController@destroy')->name('delete');
        });
    });
});


// for frontend:
Route::prefix('settings')->group(function () {
    Route::get('/', 'SettingsController@index');
});

Http/Controllers/Backend/SettingsController.php
<?php

namespace Modules\Settings\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Settings\Entities\Setting;
use Illuminate\Support\Facades\App;
use Carbon\Carbon;

class SettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('settings::backend.index');
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $rules = Setting::getValidationRules();
        //ddd($rules);
        $data = $request->validate($rules);
        //dd($request);
        $validSettings = array_keys($rules);

        $fields = Setting::getDefinedSettingFields();
        //ddd($fields);
        
        foreach ($fields as $key => $item) {
            if (in_array($item['name'], $validSettings)) {
                Setting::add($item['name'], (isset($data[$item['name']]) ? $data[$item['name']] : ''), Setting::getDataType($item['name']));
            } elseif (!isset($item['rules']) && ($item['type'] == 'check' || $item['type'] == 'checkbox' || $item['type'] == 'switch')) {
                // no rule existing for this and "bool"?
                //echo isset($data[$item['name']])? 'true':'false'; exit;
                //dd($item);
                //echo $request->input($item['name'],'false'); exit;
                //$data[$item['name']] = isset($data[$item['name']])? 'true':'false';
                Setting::add($item['name'], $request->input($item['name'], 'false'), Setting::getDataType($item['name']));
            }
        }
        /*
        foreach ($data as $key => $val) {
            if (in_array($key, $validSettings)) {
                Setting::add($key, $val, Setting::getDataType($key));
            }
        }
        */

        return redirect()->back()->withFlashSuccess(__('alerts.backend.data.saved'));
    }
}

Resources/views/backend/index.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | '.__('settings::general.name')  )

@section('breadcrumb-links')

@endsection



@section('content')
    <div class="row mt-4" id="backend-settings">
        <div class="col">
            <div class="card">

                <div class="card-header">

                    <div class="row">
                        <div class="col-sm-6">
                            <h4 class="card-title mb-4">
                                <i class="fas fa-cogs text-primary"></i> {{ __( 'settings::general.name' ) }} <small class="faded"><small>{{ config('settings.name') }} | {{ setting('app_name') }}</small></small>
                            </h4>
                        </div><!--col-->
                        <div class="col-sm-6">
                            <div class="btn-toolbar float-right" role="toolbar" aria-label="@lang('labels.general.toolbar_btn_groups')">

                            </div><!--btn-toolbar-->
                        </div><!--col-->
                    </div><!--row-->

                    <ul class="nav nav-tabs card-header-tabs" role="tablist">
                        @foreach(config('settingsfields') as $section => $fields)
                            @if(!data_get($fields,'hidden',false))
                            <li class="nav-item">
                                <a class="nav-link @if($loop->index == 0) active @endif"
                                   data-toggle="tab"
                                   role="tab"
                                   href="#tab-{{$loop->index}}">
                                    <i class="{{ Arr::get($fields, 'icon', 'icon icon-settings') }}"></i>
                                    @lang(data_get($fields,'title').'')
                                </a>
                            </li>
                            @endif
                        @endforeach
                    </ul>
                </div>

                <form method="post"
                          {{--action="{{ route('admin.settings.store') }}"--}}
                          class="form-horizontal"
                          role="form">
                        {!! csrf_field() !!}

                    <div class="card-body">

                        <div class="tab-content" style="border: 0px solid #d4d3d3;">
                            @if(count(config('settingsfields', [])) )

                                @foreach(config('settingsfields') as $section => $fields)
                                    <div class="tab-pane fade card card-info @if($loop->index == 0) show active @endif"
                                         role="tabpanel"
                                         style="padding: 1rem;"
                                         id="tab-{{$loop->index}}">

                                        <div class="row">
                                            <div class="col-md-12">
                                                @foreach($fields['elements'] as $field)

                                                    @includeIf('settings::backend.fields.' . $field['type'])
                                                    @unless($loop->last)
                                                        <hr/>
                                                    @endunless
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                <!-- end panel for {{ $fields['title'] }} -->
                                @endforeach

                            @endif
                        </div>


                    </div>


                    <div class="card-footer text-right">

                        <button class="btn-primary btn">
                            {{ __('labels.general.buttons.save') }}
                        </button>

                    </div>

                </form>

            </div>
        </div><!--col-->
    </div><!--row-->
@endsection

@push('after-scripts')
<script>

$(function(){
    var hash = window.location.hash;
    hash && $('ul.nav a[href="' + hash + '"]').tab('show');

    $('.nav-tabs a').click(function (e) {
      $(this).tab('show');
      var scrollmem = $('body').scrollTop() || $('html').scrollTop();
      window.location.hash = this.hash;
      $('html,body').scrollTop(scrollmem);
    });
  });

</script>
@endpush